<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>disable</ImplicitUsings>
		<AssemblyName>ampersand</AssemblyName>
		<RootNamespace>Ampersand</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia" Version="12.*" />
		<PackageReference Include="Avalonia.Desktop" Version="12.*" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="12.*" />
		<PackageReference Include="AvaloniaTerminal" Version="*" />
		<PackageReference Include="Porta.Pty" Version="*" />
	</ItemGroup>

	<ItemGroup>
		<None Include="apps\**" CopyToOutputDirectory="Never" />
	</ItemGroup>

</Project>
